### ISSUE TITLE
example: 'getQueueLength': is not a member of 'ofxImageSequenceRecorder_<ofShortPixels>'

### ISSUE THREAD

**Issue by paul-ferragut** [mattfelsen/ofxDepthCamera#1]
Hi 
The addon looks very useful but I am not managing to compile the example I am getting errors related to 'ofxImageSequenceRecorder'
Error   C2039   'getQueueLength': is not a member of 'ofxImageSequenceRecorder_<ofShortPixels>' example 

if I try to comment '&& !recorder.getQueueLength()'' I get the following errors
Error   C2955   'QueuedImage': use of class template requires template argument list  
Error   C2955   'QueuedImage': use of class template requires template argument list  
Error   C2512   'QueuedImage': no appropriate default constructor available example 
Error   C2664   'voidstd::queue<QueuedImage<PixelType>,std::deque<_Ty,std::allocator<_Ty>>>::push(const QueuedImage<PixelType> &)': cannot convert argument 1 from 'QueuedImage' to 'QueuedImage<PixelType> &&' 

I am using ofxImageSequenceRecorder from here: https://github.com/mattfelsen/ofxImageSequenceRecorder/tree/templated

**Comment by mattfelsen** [comment]
Hi @paul-ferragut. I might've forgotten to push a commit for that function. I'll take a look either later today or tomorrow. If you wanted to keep going on the meantime, I think that function just returned q.size()!

Thanks for checking this out. Which cam are you working with? Currently there's only an adapter for KinectV2 but it should be pretty easy to get a couple others in there soon.

**Comment by paul-ferragut** [comment]
Thanks for your reply.
I am using kinectV2 with ofxKinectForWindows2, I am interested testing with kinect 1 too!

**Comment by mattfelsen** [comment]
Hi again. I just pushed a couple commits to ofxImageSequenceRecorder which should take care of this. Can you pull there, try again, and let me know if you're still having issues?

**Comment by paul-ferragut** [comment]
thanks for the fix! I managed to compile and test the example :)
unrelated I was looking to draw point cloud with color, is there an existing way to do it with your addon?

**Comment by mattfelsen** [comment]
Great, glad to hear it :+1: 

Regarding the point clouds, there's nothing implemented yet. I haven't put too much thought in how to deal with coordinate mapping...ideally I'd like something with the simplicity of ofxKinect's getWorldCoordinateAt() since it's straightforward and has been in use for a while, but also allows you to specify whether you're coming from depth or color spaces if those sizes differ
